# Generated by Django 6.0.3 on 2026-03-06 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, default='', max_length=255)),
                ('group', models.CharField(blank=True, default='', max_length=255)),
                ('parent_group', models.CharField(blank=True, default='', max_length=255)),
                ('tax_category', models.CharField(choices=[('gst', 'GST'), ('tds', 'TDS'), ('tcs', 'TCS'), ('none', 'None')], default='none', max_length=10)),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('gst_registration_type', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tally_guid', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_ledgers', to='clients.clientprofile')),
            ],
            options={
                'db_table': 'sizh_tally_ledgers',
                'ordering': ['name'],
                'unique_together': {('client_profile', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text="Keyword/narration pattern to match (e.g. 'Salary', 'NEFT-ABC Corp')", max_length=500)),
                ('rule_type', models.CharField(choices=[('payment', 'Payment'), ('receipt', 'Receipt'), ('contra', 'Contra'), ('journal', 'Journal'), ('sales', 'Sales'), ('purchase', 'Purchase')], default='payment', max_length=20)),
                ('from_field', models.CharField(blank=True, default='', help_text='Source field value / from account', max_length=255)),
                ('to_field', models.CharField(blank=True, default='', help_text='Destination field value / to account', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules match first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='clients.clientprofile')),
                ('target_ledger', models.ForeignKey(blank=True, help_text='Tally Ledger to auto-assign when this rule matches', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='masters.tallyledger')),
            ],
            options={
                'db_table': 'sizh_rules',
                'ordering': ['-priority', 'description'],
            },
        ),
        migrations.CreateModel(
            name='TallyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, default='', max_length=255)),
                ('group', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('uom', models.CharField(blank=True, default='', max_length=50)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=20)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tally_guid', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_items', to='clients.clientprofile')),
            ],
            options={
                'db_table': 'sizh_tally_items',
                'ordering': ['name'],
                'unique_together': {('client_profile', 'name')},
            },
        ),
    ]
