# Generated by Django 6.0.3 on 2026-03-09 07:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientprofile_industry_type'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nature', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sizh_ledger_groups',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sub_category', models.CharField(blank=True, default='', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_custom', models.BooleanField(default=False, help_text='True if manually added by the CA (not from template)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ledgers', to='clients.clientprofile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ledgers', to='masters.ledgergroup')),
            ],
            options={
                'db_table': 'sizh_client_ledgers',
                'ordering': ['group', 'name'],
                'unique_together': {('client_profile', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LedgerTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry_type', models.CharField(blank=True, db_index=True, default='', help_text='Blank = common to all industries', max_length=20)),
                ('sub_category', models.CharField(blank=True, default='', help_text='Grouping label: GST, General Expenses, Parties, etc.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='masters.ledgergroup')),
            ],
            options={
                'db_table': 'sizh_ledger_templates',
                'ordering': ['group', 'name'],
                'unique_together': {('name', 'industry_type')},
            },
        ),
    ]
