# Generated by Django 6.0.3 on 2026-03-05 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, default='', max_length=255)),
                ('pan', models.CharField(blank=True, default='', max_length=10)),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('gst_type', models.CharField(choices=[('regular', 'Regular'), ('composition', 'Composition'), ('unregistered', 'Unregistered'), ('isd', 'Input Service Distributor')], default='regular', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.TextField(blank=True, default='')),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('financial_year_start', models.DateField(blank=True, null=True)),
                ('tally_company_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sizh_client_profiles',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'gstin')},
            },
        ),
    ]
