# Generated by Django 6.0.3 on 2026-03-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('trading', 'Trading'), ('service', 'Service'), ('ecommerce', 'E-commerce'), ('manufacturing', 'Manufacturing')], default='', help_text='Business type / industry for smart ledger suggestions', max_length=20),
        ),
    ]
