# Generated by Django 6.0.3 on 2026-03-06 07:38

import django.db.models.deletion
import transactions.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(choices=[('banking', 'Banking'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('sales_return', 'Sales Return'), ('purchase_return', 'Purchase Return'), ('journal', 'Journal'), ('ledger', 'Ledger'), ('items', 'Items')], max_length=20)),
                ('bank_account', models.CharField(blank=True, default='', help_text='Bank ledger name (for banking voucher type)', max_length=255)),
                ('file', models.FileField(upload_to=transactions.models.upload_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('mapping', 'Field Mapping'), ('mapped', 'Mapped'), ('ai_processing', 'AI Processing'), ('ready', 'Ready for Review'), ('approved', 'Approved'), ('sent_to_tally', 'Sent to Tally'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('source_headers', models.JSONField(blank=True, null=True)),
                ('field_mapping', models.JSONField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_jobs', to='clients.clientprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sizh_upload_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('place_of_supply', models.CharField(blank=True, default='', max_length=100)),
                ('ledger_source', models.CharField(blank=True, choices=[('manual', 'Manual'), ('rule', 'Rule'), ('ai', 'AI Suggested')], default='', max_length=10)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('assigned_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_rows', to='masters.tallyledger')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='transactions.uploadjob')),
            ],
            options={
                'db_table': 'sizh_transaction_rows',
                'ordering': ['row_number'],
            },
        ),
    ]
