# Generated by Django 6.0.3 on 2026-03-07 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrow',
            name='hsn_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transactionrow',
            name='invoice_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transactionrow',
            name='ledger_name',
            field=models.CharField(blank=True, default='', help_text='Gemini-suggested ledger name (before matching to TallyLedger)', max_length=255),
        ),
        migrations.AddField(
            model_name='transactionrow',
            name='narration',
            field=models.TextField(blank=True, default='', help_text='Full narration / particulars for Tally'),
        ),
        migrations.AddField(
            model_name='transactionrow',
            name='party_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactionrow',
            name='voucher_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transactionrow',
            name='voucher_type',
            field=models.CharField(blank=True, default='', help_text='Tally voucher type: Payment, Receipt, Contra, Journal, Sales, Purchase, Credit Note, Debit Note', max_length=30),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='detected_document_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='gemini_raw_response',
            field=models.TextField(blank=True, default='', help_text='Raw JSON string returned by Gemini for audit trail'),
        ),
        migrations.AlterField(
            model_name='transactionrow',
            name='ledger_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('rule', 'Rule'), ('ai', 'AI Suggested'), ('gemini', 'Gemini Extracted')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadjob',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('ocr_processing', 'OCR Processing'), ('ocr_done', 'OCR Done'), ('mapping', 'Field Mapping'), ('mapped', 'Mapped'), ('ai_processing', 'AI Processing'), ('ready', 'Ready for Review'), ('approved', 'Approved'), ('sent_to_tally', 'Sent to Tally'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.CreateModel(
            name='TallyVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Contra', 'Contra'), ('Journal', 'Journal'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Credit Note', 'Credit Note'), ('Debit Note', 'Debit Note')], max_length=30)),
                ('voucher_number', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('party_ledger_name', models.CharField(help_text="Tally 'Party A/c Name' – the main debit/credit ledger", max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_debit', models.BooleanField(help_text='True if this is a debit entry for party_ledger_name')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('place_of_supply', models.CharField(blank=True, default='', max_length=100)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=20)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('counter_ledger_name', models.CharField(blank=True, default='', help_text='Tally ledger for the opposite side (e.g. Bank A/c for payments)', max_length=255)),
                ('counter_amount', models.DecimalField(decimal_places=2, default=0, help_text="Amount for counter-entry (usually equals 'amount')", max_digits=15)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent to Tally'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('tally_master_id', models.CharField(blank=True, default='', help_text='GUID returned by Tally after successful import', max_length=255)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('tally_xml', models.TextField(blank=True, default='', help_text='Complete Tally XML envelope for this voucher')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_vouchers', to='clients.clientprofile')),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='transactions.uploadjob')),
                ('source_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='transactions.transactionrow')),
            ],
            options={
                'db_table': 'sizh_tally_vouchers',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['client_profile', 'sync_status'], name='sizh_tally__client__774ffb_idx'), models.Index(fields=['date'], name='sizh_tally__date_92fca2_idx')],
            },
        ),
    ]
